---
- name: 'web-app installing with playbook'
  hosts: 127.0.0.1
# tasks file for consul install
  tasks:

    - name: "Add nodejs" 
      shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
      #warn: false
      # update_cache: yes
      become: yes

      #    - name: add trusted key
      #shell: wget -O- https://dl.bintray.com/rabbitmq/Keys/rabbitmq-release-signing-key.asc | sudo apt-key add -
      #become: yes
    - name: 'Installing nodejs'
      apt:
        name: nodejs
        state: present
        update_cache: yes
      become: yes
    
    - name: install angular
      shell: npm install -g @angular/cli
      become: yes
    
    - name: install angular dev-kit
      shell: npm install --save-dev @angular-devkit/build-angular
      become: yes
    
    - name: check repo exist or not
      stat:
        path: "web-app-epam/"
      register: repoexist
        
    - name: git clone
      shell: git clone https://github.com/Norik-Chichyan/web-app-epam.git
      when: not repoexist.stat.exists

      #    - name: change dir 
      #      shell: cd web-app-epam/
    
    - name: build angular
      shell: npm run build --prefix web-app-epam/

      #    - name: nmp audit fix 
      #      shell: npm audit fix --force web-app-epam/
    
    - name: ng listenting ip
      shell: cd web-app-epam/ && ng serve --host 0.0.0.0
